from .OptionPackage.OptionPortfolioClass import OptionPortfolio


# In this file we store some global variables


# The portfolio

portfolio = None


# The plot that might be generated by the GPT

plots = []